### ISSUE TITLE
Not a valid font file error message in Windows 10

### ISSUE THREAD

**Issue by carlanwray** [edenberger/Robo-PaleoHeb#1]
I am getting the following error:

The requested file C:\Heebo-Thin_Paleo.ttf is not a valid font file.

Windows 10 Pro

Thanks all of your work on this, it looks amazing!

**Comment by paulocoutinhox** [comment]
This font is not working...

**Comment by edenberger** [comment]
Hey I updated it, you can test again.

Thanks (;
